# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\computo2Progra\EjercicioPropio\ejerciciopropio.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TallerCocolito(object):
    def setupUi(self, TallerCocolito):
        TallerCocolito.setObjectName("TallerCocolito")
        TallerCocolito.resize(721, 261)
        self.centralwidget = QtWidgets.QWidget(TallerCocolito)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(210, 60, 131, 22))
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lblTptrabajo = QtWidgets.QLabel(self.centralwidget)
        self.lblTptrabajo.setGeometry(QtCore.QRect(90, 60, 101, 16))
        self.lblTptrabajo.setObjectName("lblTptrabajo")
        self.lblNombre = QtWidgets.QLabel(self.centralwidget)
        self.lblNombre.setGeometry(QtCore.QRect(90, 22, 101, 21))
        self.lblNombre.setObjectName("lblNombre")
        self.inNombre = QtWidgets.QLineEdit(self.centralwidget)
        self.inNombre.setGeometry(QtCore.QRect(210, 20, 251, 20))
        self.inNombre.setObjectName("inNombre")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(490, 20, 160, 141))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.totalLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.totalLayout.setContentsMargins(0, 0, 0, 0)
        self.totalLayout.setObjectName("totalLayout")
        self.lblPrecioMaterial = QtWidgets.QLabel(self.centralwidget)
        self.lblPrecioMaterial.setGeometry(QtCore.QRect(90, 100, 91, 16))
        self.lblPrecioMaterial.setObjectName("lblPrecioMaterial")
        self.inNombre_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.inNombre_2.setGeometry(QtCore.QRect(210, 100, 251, 20))
        self.inNombre_2.setObjectName("inNombre_2")
        self.lblPrecioMaterial_2 = QtWidgets.QLabel(self.centralwidget)
        self.lblPrecioMaterial_2.setGeometry(QtCore.QRect(90, 140, 101, 16))
        self.lblPrecioMaterial_2.setObjectName("lblPrecioMaterial_2")
        self.inMano = QtWidgets.QLineEdit(self.centralwidget)
        self.inMano.setGeometry(QtCore.QRect(210, 140, 241, 20))
        self.inMano.setObjectName("inMano")
        self.lblPrecioMaterial_3 = QtWidgets.QLabel(self.centralwidget)
        self.lblPrecioMaterial_3.setGeometry(QtCore.QRect(90, 180, 61, 16))
        self.lblPrecioMaterial_3.setObjectName("lblPrecioMaterial_3")
        self.txtPrecioFinal = QtWidgets.QLineEdit(self.centralwidget)
        self.txtPrecioFinal.setGeometry(QtCore.QRect(210, 180, 241, 20))
        self.txtPrecioFinal.setObjectName("txtPrecioFinal")
        self.radioSinDescuento = QtWidgets.QRadioButton(self.centralwidget)
        self.radioSinDescuento.setGeometry(QtCore.QRect(490, 180, 111, 17))
        self.radioSinDescuento.setObjectName("radioSinDescuento")
        self.radioConDescuento = QtWidgets.QRadioButton(self.centralwidget)
        self.radioConDescuento.setGeometry(QtCore.QRect(590, 180, 111, 17))
        self.radioConDescuento.setObjectName("radioConDescuento")
        TallerCocolito.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TallerCocolito)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 721, 21))
        self.menubar.setObjectName("menubar")
        TallerCocolito.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TallerCocolito)
        self.statusbar.setObjectName("statusbar")
        TallerCocolito.setStatusBar(self.statusbar)

        self.retranslateUi(TallerCocolito)
        QtCore.QMetaObject.connectSlotsByName(TallerCocolito)

    def retranslateUi(self, TallerCocolito):
        _translate = QtCore.QCoreApplication.translate
        TallerCocolito.setWindowTitle(_translate("TallerCocolito", "MainWindow"))
        self.comboBox.setItemText(0, _translate("TallerCocolito", "Puerta"))
        self.comboBox.setItemText(1, _translate("TallerCocolito", "Porton"))
        self.comboBox.setItemText(2, _translate("TallerCocolito", "Balcon"))
        self.comboBox.setItemText(3, _translate("TallerCocolito", "otro"))
        self.lblTptrabajo.setText(_translate("TallerCocolito", "Tipo de trabajo"))
        self.lblNombre.setText(_translate("TallerCocolito", "nombre del cliente"))
        self.lblPrecioMaterial.setText(_translate("TallerCocolito", "Precio del material: "))
        self.lblPrecioMaterial_2.setText(_translate("TallerCocolito", "Precio Mano de obra:  "))
        self.lblPrecioMaterial_3.setText(_translate("TallerCocolito", "Precio Final:  "))
        self.radioSinDescuento.setText(_translate("TallerCocolito", "Descunento"))
        self.radioConDescuento.setText(_translate("TallerCocolito", "Descunento"))
