# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\computo2Progra\Ejercicio4\Ejercicio4.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(577, 255)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnSubir = QtWidgets.QPushButton(self.centralwidget)
        self.btnSubir.setGeometry(QtCore.QRect(190, 160, 75, 23))
        self.btnSubir.setObjectName("btnSubir")
        self.Dato1 = QtWidgets.QLabel(self.centralwidget)
        self.Dato1.setGeometry(QtCore.QRect(30, 40, 141, 16))
        self.Dato1.setObjectName("Dato1")
        self.Dato2 = QtWidgets.QLabel(self.centralwidget)
        self.Dato2.setGeometry(QtCore.QRect(30, 80, 141, 16))
        self.Dato2.setObjectName("Dato2")
        self.Dato3 = QtWidgets.QLabel(self.centralwidget)
        self.Dato3.setGeometry(QtCore.QRect(30, 120, 131, 16))
        self.Dato3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Dato3.setObjectName("Dato3")
        self.intDato1 = QtWidgets.QLineEdit(self.centralwidget)
        self.intDato1.setGeometry(QtCore.QRect(180, 40, 141, 20))
        self.intDato1.setObjectName("intDato1")
        self.intDato2 = QtWidgets.QLineEdit(self.centralwidget)
        self.intDato2.setGeometry(QtCore.QRect(180, 80, 141, 20))
        self.intDato2.setObjectName("intDato2")
        self.intDato3 = QtWidgets.QLineEdit(self.centralwidget)
        self.intDato3.setGeometry(QtCore.QRect(180, 120, 141, 20))
        self.intDato3.setObjectName("intDato3")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(360, 30, 171, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.mascota1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.mascota1.setContentsMargins(0, 0, 0, 0)
        self.mascota1.setObjectName("mascota1")
        self.salida1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.salida1.setObjectName("salida1")
        self.mascota1.addWidget(self.salida1)
        self.salida2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.salida2.setObjectName("salida2")
        self.mascota1.addWidget(self.salida2)
        self.salida3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.salida3.setObjectName("salida3")
        self.mascota1.addWidget(self.salida3)
        self.otroRegistro = QtWidgets.QPushButton(self.centralwidget)
        self.otroRegistro.setGeometry(QtCore.QRect(40, 160, 91, 23))
        self.otroRegistro.setObjectName("otroRegistro")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 577, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnSubir.setText(_translate("MainWindow", "Registrar"))
        self.Dato1.setText(_translate("MainWindow", "Primer dato de la mascota"))
        self.Dato2.setText(_translate("MainWindow", "segundo dato de la mascota"))
        self.Dato3.setText(_translate("MainWindow", "Tercer dato de la mascota"))
        self.salida1.setText(_translate("MainWindow", "dato 1: "))
        self.salida2.setText(_translate("MainWindow", "dato 2: "))
        self.salida3.setText(_translate("MainWindow", "dato 3: "))
        self.otroRegistro.setText(_translate("MainWindow", "otra mascota"))
