# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\computo2Progra\Ejercicio1\Ejercicio1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ejercicio1(object):
    def setupUi(self, Ejercicio1):
        Ejercicio1.setObjectName("Ejercicio1")
        Ejercicio1.resize(472, 217)
        self.centralwidget = QtWidgets.QWidget(Ejercicio1)
        self.centralwidget.setObjectName("centralwidget")
        self.Nombre2 = QtWidgets.QLabel(self.centralwidget)
        self.Nombre2.setEnabled(True)
        self.Nombre2.setGeometry(QtCore.QRect(90, 100, 73, 19))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.Nombre2.setFont(font)
        self.Nombre2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Nombre2.setObjectName("Nombre2")
        self.NombreCALC_2 = QtWidgets.QLabel(self.centralwidget)
        self.NombreCALC_2.setGeometry(QtCore.QRect(170, 100, 151, 16))
        self.NombreCALC_2.setObjectName("NombreCALC_2")
        self.Edada1 = QtWidgets.QLabel(self.centralwidget)
        self.Edada1.setEnabled(True)
        self.Edada1.setGeometry(QtCore.QRect(320, 70, 73, 19))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.Edada1.setFont(font)
        self.Edada1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Edada1.setObjectName("Edada1")
        self.Edad2 = QtWidgets.QLabel(self.centralwidget)
        self.Edad2.setEnabled(True)
        self.Edad2.setGeometry(QtCore.QRect(320, 100, 73, 19))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.Edad2.setFont(font)
        self.Edad2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Edad2.setObjectName("Edad2")
        self.Nombre1 = QtWidgets.QLabel(self.centralwidget)
        self.Nombre1.setEnabled(True)
        self.Nombre1.setGeometry(QtCore.QRect(90, 70, 73, 19))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.Nombre1.setFont(font)
        self.Nombre1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Nombre1.setObjectName("Nombre1")
        self.NombreCALC = QtWidgets.QLabel(self.centralwidget)
        self.NombreCALC.setGeometry(QtCore.QRect(170, 70, 151, 16))
        self.NombreCALC.setObjectName("NombreCALC")
        Ejercicio1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Ejercicio1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 472, 21))
        self.menubar.setObjectName("menubar")
        Ejercicio1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Ejercicio1)
        self.statusbar.setObjectName("statusbar")
        Ejercicio1.setStatusBar(self.statusbar)

        self.retranslateUi(Ejercicio1)
        QtCore.QMetaObject.connectSlotsByName(Ejercicio1)

    def retranslateUi(self, Ejercicio1):
        _translate = QtCore.QCoreApplication.translate
        Ejercicio1.setWindowTitle(_translate("Ejercicio1", "Ejercicio 1"))
        self.Nombre2.setText(_translate("Ejercicio1", "Nombre: 2"))
        self.NombreCALC_2.setText(_translate("Ejercicio1", "Josué Roberto Villegas Duran"))
        self.Edada1.setText(_translate("Ejercicio1", "Edad:20"))
        self.Edad2.setText(_translate("Ejercicio1", "Edad:19"))
        self.Nombre1.setText(_translate("Ejercicio1", "Nombre: 1"))
        self.NombreCALC.setText(_translate("Ejercicio1", "Carlos Aristides Larin Cañas"))
